### ISSUE TITLE
Can't update the backend up to v4.0.0: MONGODB_XXX_REPLICA_SET variables

### ISSUE THREAD

**Issue by alexcustos** [linagora/linshare-backend-dockerfile#1]
Hello, I found nothing about `MONGODB_DATA_REPLICA_SET` and `MONGODB_SMALLFILES_REPLICA_SET` variables, which are mandatory for the latest version. The `Dockerfile` doesn't have defaults, and it's not clear what `start.sh` expects. Can you please suggest what I should specify to upgrade the backend from the previous version.

**Comment by fmartin-linagora** [comment]
Hi,
We released LinShare 4.0 Friday, we planned to update the docker compose this week.
Indeed, we forgot to update the readme about these new variables. If you have lauched the backen dimage with old env varialbes like MONGODB_URI, you should have seen a deprecated warning telling you to use  MONGODB_DATA_REPLICA_SET.
Samples:
MONGODB_DATA_REPLICA_SET=host1:27017
MONGODB_DATA_REPLICA_SET=host1:27017/?replicaSet=test
MONGODB_DATA_REPLICA_SET=host1:27017,host2:27017;host2:27017/?replicaSet=test

**Comment by alexcustos** [comment]
@fmartin-linagora Thank you, I synced my settings with the latest docker-compose.yml and everything was updated smoothly (that's not my first Postgres and Mongo containers), but I found LDAP Connections was the only setting preserved, everything else including the admin password was reset to its defaults, no domain and so on. That's not a big issue. I'm just wondering if it was intended behavior.

**Comment by fmartin-linagora** [comment]
Hi,
Only the root password is reset during the upgrade 2.3 to 4.0. all settings and data are kept. I will update the docker-compose and test the upgrade process after august holidays ;)

I've just updated the documentation about mongo here https://github.com/linagora/linshare-backend-dockerfile/commit/cccfaab942aa50828e7a4aef5a5d3579ccc75338

**Comment by fmartin-linagora** [comment]
Documentation was fixed: https://github.com/linagora/linshare-backend-dockerfile/blob/master/README.md
